name: adversarial-driving
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.0
  - pip
  - pip:
    - eventlet==0.29.1
    - flask==2.1.0
    - flask-cors==3.0.9
    - flask-socketio==4.3.1
    - future==0.18.2
    - grpcio==1.33.2
    - h5py==2.10.0
    - keras==2.4.3
    - keras-preprocessing==1.1.2
    - matplotlib==3.3.3
    - numpy
    - opencv-python==4.4.0.46
    - pandas==1.1.4
    - pillow==8.0.1
    - protobuf==3.14.0
    - python-socketio==4.6.0
    - scikit-learn==0.22.2
    - scipy==1.4.1
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - greenlet==0.4.17
    - python-engineio==3.13.2
    - urllib3==1.26.2
